services:
  
  2dgc_id:
    container_name: 2dgc_id_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8888:8888"
    volumes:
    - type: bind
      source: ${HOST_VOLUME_PATH}/
      # target: ${DOCKER_VOLUME_PATH}/
      target: /app/GCxGC_MS/DATA
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env