FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY config/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

COPY . .

EXPOSE 8888

CMD ["jupyter", "lab", \
    "--notebook-dir=/app/notebooks", \
    "--ip=0.0.0.0", \
    "--port=8888", \
    "--allow-root"]