FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install voila

EXPOSE 8888

# CMD ["jupyter", "lab", "--notebook-dir=/app/notebooks", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token=''"]
CMD ["voila", "notebooks/interface_peak_detection_new.ipynb", "--port=8888", "--no-browser", "--allow-root"] 