services:

  nist:
    image: pywine-pyms-nist-mainlib
    build:
      context: .
      dockerfile: Dockerfile.nist
    container_name: nist_engine
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - type: bind
        source: /home/camille/Documents/volume_data/mainlib
        target: /app/data/mainlib
      - type: bind
        source: /home/camille/Documents/volume_data/tmp
        target: /app/data/tmp
        # ICI ajout
      - type: bind
        source: /home/camille/Documents/volume_data/
        target: /app/data/
    environment:
      - LIBTYPE=1 # 1: mainlib, 2: sublib
    networks:
      - nist_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  2dgc_id:
    image: 2dgc_id-app
    container_name: 2dgc_id_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
    - type: bind
      source: /home/camille/Documents/volume_data/
      target: /app/data
    - type: bind
      source: .
      target: /app
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    depends_on:
      nist:
        condition: service_healthy
    networks:
      - nist_network

networks:
  nist_network:
    driver: bridge
  